name: Build IOS
run-name: Build IOS
on:
  workflow_dispatch: {}
jobs:
  Build_IOS:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: sudo xcode-select --switch /Applications/Xcode_14.3.1.app
    - run: flutter pub get
    - run: |
        flutter build ios --release --no-codesign
        cd build/ios/iphoneos
        mkdir Payload
        cd Payload
        ln -s ../Runner.app
        cd ..
        zip -r app-release.ipa Payload
    

    - uses: actions/upload-artifact@v3
      with:
        name: app-release.ipa
        path: "build/ios/iphoneos/app-release.ipa"
